### ISSUE TITLE
Inconsistent linking of METIS

### ISSUE THREAD

**Issue by mcopik** [elemental/Elemental#114]
Hi!

Our team found another small issue with Elemental at our cluster. It's not a bug, but we're not sure if it is absolutely normal and expected by developers of Elemental. Also the inconsistent behaviour of build system is a little bit confusing for us.

Our situation: we have a METIS available at the cluster at standard location, i.e. /usr/lib64/libmetis.so; for now let's assume that we never want to use it. During default build when CMake obtains only paths to C, C++ compilers and installation directory, the script FindParMETIS.cmake is called to locate this library. Of course it fails to find an instance of ParMETIS in the system, but CMake is able to find [installed version of METIS](https://github.com/elemental/Elemental/blob/master/cmake/modules/FindParMETIS.cmake#L82) and the variable `METIS_LIBRARY` containing path to METIS is stored in cache (I confirmed this by getting additional output from CMake scripts). Later, ParMETIS is pulled from a Git repository, configured as an external project and Elemental [uses an instance of METIS built by ParMETIS](https://github.com/elemental/Elemental/blob/master/cmake/external_projects/ElMath/ParMETIS.cmake#L103). It's absolutely fine and the configuration script ElVars confirms that linking flag contains both ParMETIS and METIS stored at installation directory of Elemental.

The inconsistency appears when CMake reconfigures itself, e.g. after any change in scripts files. The ParMETIS instance is found, but [the check for METIS is not done](https://github.com/elemental/Elemental/blob/master/cmake/modules/FindParMETIS.cmake#L81), because this variable is already in cache. Now the linking flags in configuration file contain: `some_install_directory/lib/libparmetis.so /usr/lib64/libmetis.so`.

We can't say that it's a bug. Personally, I've run into problems twice in our separate project which is based on Elemental, but it's also quite likely that it was my mistake - I can't reproduce this issue right now and prove that indeed the linking was the problem.

If the linking flags provided in conf/ElVars are used, then linker will be forced to use the **instance of METIS at system path**. But if a rpath or LD_LIBRARY_PATH is modified to point at Elemental's install directory, then during runtime **an instance of METIS from Elemental will be used**. Is it safe to assume that it won't cause any problems in the future? I can easily create a scenario when this procedure blows up the application and produces strange errors, but I don't know if it's going to happen with METIS and Elemental.

**Comment by poulson** [comment]
Thanks for another insightful build system suggestion Marcin. I just committed the following changeset which should alleviate the `METIS_LIBRARY` and `METIS_INCLUDE_DIR` caching issue: https://github.com/elemental/Elemental/commit/374a588764b8acf2067a057a7136206f7603b83a

**Comment by mcopik** [comment]
Dear Jack,

thanks for your response! However, the commit doesn't resolve the issue. find_library creates a cached variable so the unset functions must be called as: `unset(variable_name CACHE)`.

**Comment by poulson** [comment]
Easy enough! https://github.com/elemental/Elemental/commit/9d84014e843da29abd4832fef9eebba75a545dc9

**Comment by mcopik** [comment]
Unfortunately, it doesn't resolve the issue. The problem is that the installation location for ParMETIS is not stored in cache; the variables `PARMETIS_DIR` and `PARMETIS_LIB_DIR` are empty when the ParMETIS is built automatically, which means that [hints for header/libraries lookup are empty](https://github.com/elemental/Elemental/blob/master/cmake/modules/FindParMETIS.cmake#L52). According to CMake documentation, it will add the installation directory of Elemental to `CMAKE_SYSTEM_PREFIX_PATH`, but locations specified by this variable are the very last position on a list of directories to check, even after system paths. In this configuration METIS installation in system is preferred over the one provided by ParMETIS.

I've found four issues here:

1. When ParMETIS is pulled from git repository and built with METIS, the installation path needs to be defined in cache so it can be used for hints.

2. [Because of a typo](https://github.com/elemental/Elemental/blob/master/cmake/modules/FindParMETIS.cmake#L59) the include directory for METIS has been incorrectly detected to be the correct one (installation directory) because it's looking for parmetis.h, not metis.h. Otherwise it should find /usr/include.

3. [I believe that the update of `PARMETIS_INCLUDE_DIR`](https://github.com/elemental/Elemental/blob/master/cmake/external_projects/ElMath/ParMETIS.cmake#L96) doesn't have any effect on cache - it has been already defined in cache by find_path and contains `PARMETIS_INCLUDE_DIR-NOTFOUND `. This variable is used locally, but after the reconfiguration FindParMETIS looks again for ParMETIS headers. This could be solved by calling the set function() with CACHE and FORCE parameters. CMake will search again for ParMETIS library file too, because there is no definition of PARMETIS_LIBRARY in cache. 

4. find_path for `metis.h` is using hints: `${METIS_DIR} ${METIS_INCLUDE_DIR}`. On the other hand, find_library for libmetis is using hints: `${PARMETIS_LIB_DIR} ${PARMETIS_DIR}`.

Pull request #115 fixes first and second issue. Third issue - it's not really a problem, I'm just giving you my observation because I don't know if this is how it should work. Fourth issue - it's probably a bug, but I'm not sure which version (look in ParMETIS or METIS directory) is correct. If the second version is correct, then my solution f7a5249c12a18d7bb8d063b29da43036bb355e06 should be extended with a counterpart for for METIS directory.

**Comment by poulson** [comment]
Thanks again, Marcin. You've clearly tested the external METIS/ParMETIS options more than I have; I tend to always build them from scratch in my tests, though integration with PETSc's ParMETIS had also been made to work. I'm not really sure on what the best behavior for (3) should be either; perhaps it's okay as-is for now?

**Comment by mcopik** [comment]
Personally, I believe that's absolutely fine. I just wanted to make you sure that this behaviour is expected ;) Many thanks for your help! I'm closing the issue.
